name: CI/CD Pipeline for AWS Lambda

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Altere para a versão do Python que sua função Lambda utiliza

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Certifique-se de ter um requirements.txt na raiz do seu repositório

      # Step 4: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Altere para a região que você está utilizando

      # Step 5: Package the Lambda function
      - name: Package Lambda function
        run: |
          zip -r function.zip . 
          
      # Step 6: Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name AuthByCpfFunction --zip-file fileb://function.zip
